# Generated by Django 5.0.12 on 2025-03-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeatPump",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("param_name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("number_map", models.IntegerField()),
                ("type_device", models.IntegerField()),
            ],
            options={
                "db_table": "map_markers",
                "managed": False,
            },
        ),
    ]