# Generated by Django 5.2.7 on 2025-10-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_ip',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='exclusion',
            old_name='user_ip',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='ptc_id',
        ),
        migrations.RemoveField(
            model_name='exclusion',
            name='ptc_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='ptc',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exclusion',
            name='ptc',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='param',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='tura',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='exclusion',
            index=models.Index(fields=['ptc'], name='monitoring__ptc_5db70e_idx'),
        ),
        migrations.AddIndex(
            model_name='exclusion',
            index=models.Index(fields=['ptc', 'param'], name='monitoring__ptc_322b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='exclusion',
            index=models.Index(fields=['ptc', 'until'], name='monitoring__ptc_f3ca9c_idx'),
        ),
    ]
